### ISSUE TITLE
tag is not defined

### ISSUE THREAD

**Issue by foxrider1998** [Schaggo/QR-ARDUINO#1]

**Comment by foxrider1998** [comment]
identifier "TAG" is undefined
at build phase

**Comment by Schaggo** [comment]
I guess it's something with your build environment.

See src/qrcode_recognize.c //line 41

**Comment by foxrider1998** [comment]
I will check it , is it must include manualy?

Pada tanggal Rab, 1 Mar 2023 00.24, Schaggo ***@***.***>
menulis:

**Comment by Schaggo** [comment]
If you use the vs code project it should work oob.

Are you getting an include error?
